# Copyright (c) 2019 the Octant contributors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: sample
    app.kubernetes.io/version: v1
spec:
  ports:
    - port: 80
      name: web
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: sample
    app.kubernetes.io/version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: sample
    app.kubernetes.io/version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: sample
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: sample
        app.kubernetes.io/version: v1
    spec:
      containers:
        - name: nginx
          image: nginx:1.13.6
          ports:
            - containerPort: 80
          env:
            - name: DEMO_GREETING
              value: "Hello from the environment"
            - name: DEMO_FAREWELL
              value: "Such a sweet sorrow"
