apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-host-ingress
spec:
  rules:
  - host: www.mycompany.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: www-service
            port:
              number: 80
  - host: shop.mycompany.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shop-service
            port:
              number: 80
