apiVersion: v1
kind: Service
metadata:
  name: nginx-rc
  labels:
    project: kubepi
spec:
  ports:
    - port: 80
      name: web
  selector:
    app: nginx-rc
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    project: kubepi
  name: nginx
spec:
  replicas: 3
  selector:
    app: nginx-rc
  template:
    metadata:
      labels:
        app: nginx-rc
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
